# -*- coding:utf-8 -*-
import mime

from libs.choices import Enumeration
from . import strings


DISTANCE_CHOICES = Enumeration([
    (0, 'DISTANCE_1', strings.DISTANCE_CHOICES_1),
    (5, 'DISTANCE_2', strings.DISTANCE_CHOICES_2),
    (10, 'DISTANCE_3', strings.DISTANCE_CHOICES_3),
    (20, 'DISTANCE_4', strings.DISTANCE_CHOICES_4),
    (30, 'DISTANCE_5', strings.DISTANCE_CHOICES_5),
    (40, 'DISTANCE_6', strings.DISTANCE_CHOICES_6),
    (50, 'DISTANCE_7', strings.DISTANCE_CHOICES_7),
    (60, 'DISTANCE_8', strings.DISTANCE_CHOICES_8),
    (75, 'DISTANCE_9', strings.DISTANCE_CHOICES_9),
    (100, 'DISTANCE_10', strings.DISTANCE_CHOICES_10),
    (150, 'DISTANCE_11', strings.DISTANCE_CHOICES_11),
    (200, 'DISTANCE_12', strings.DISTANCE_CHOICES_12),
])

SCHEDULE_TYPE_CHOICES = Enumeration([
    (False, 'PART_TIME', strings.SCHEDULE_TYPE_CHOICES_PART_TIME),
    (True, 'FULL_TIME', strings.SCHEDULE_TYPE_CHOICES_FULL_TIME),
])

HOURLY_WAGE_CHOICES = Enumeration([
    (1, 'HOURLY_WAGE_1', strings.HOURLY_WAGE_CHOICES_1),
    (2, 'HOURLY_WAGE_2', strings.HOURLY_WAGE_CHOICES_2),
    (3, 'HOURLY_WAGE_3', strings.HOURLY_WAGE_CHOICES_3),
    (4, 'HOURLY_WAGE_4', strings.HOURLY_WAGE_CHOICES_4),
    (5, 'HOURLY_WAGE_5', strings.HOURLY_WAGE_CHOICES_5),
    (6, 'HOURLY_WAGE_6', strings.HOURLY_WAGE_CHOICES_6),
    (7, 'HOURLY_WAGE_7', strings.HOURLY_WAGE_CHOICES_7),
    (8, 'HOURLY_WAGE_8', strings.HOURLY_WAGE_CHOICES_8),
    (9, 'HOURLY_WAGE_9', strings.HOURLY_WAGE_CHOICES_9),
    (10, 'HOURLY_WAGE_10', strings.HOURLY_WAGE_CHOICES_10),
    (11, 'HOURLY_WAGE_11', strings.HOURLY_WAGE_CHOICES_11),
])

ANNUALY_WAGE_CHOICES = Enumeration([
    (1, 'ANNUALY_WAGE_1', strings.ANNUALY_WAGE_CHOICES_1),
    (2, 'ANNUALY_WAGE_2', strings.ANNUALY_WAGE_CHOICES_2),
    (3, 'ANNUALY_WAGE_3', strings.ANNUALY_WAGE_CHOICES_3),
    (4, 'ANNUALY_WAGE_4', strings.ANNUALY_WAGE_CHOICES_4),
    (5, 'ANNUALY_WAGE_5', strings.ANNUALY_WAGE_CHOICES_5),
    (6, 'ANNUALY_WAGE_6', strings.ANNUALY_WAGE_CHOICES_6),
    (7, 'ANNUALY_WAGE_7', strings.ANNUALY_WAGE_CHOICES_7),
    (8, 'ANNUALY_WAGE_8', strings.ANNUALY_WAGE_CHOICES_8),
    (9, 'ANNUALY_WAGE_9', strings.ANNUALY_WAGE_CHOICES_9),
    (10, 'ANNUALY_WAGE_10', strings.ANNUALY_WAGE_CHOICES_10),
    (11, 'ANNUALY_WAGE_11', strings.ANNUALY_WAGE_CHOICES_11),
])

COMPENSATION_TYPE_CHOICES = Enumeration([
    (False, 'HOURLY', strings.COMPENSATION_TYPE_CHOICES_HOURLY),
    (True, 'SALARY', strings.COMPENSATION_TYPE_CHOICES_SALARY),
])

EXPERIENCE_YEARS_CHOICES = Enumeration([
    (1, 'EXPERIENCE_1', strings.EXPERIENCE_YEARS_CHOICES_1),
    (2, 'EXPERIENCE_2', strings.EXPERIENCE_YEARS_CHOICES_2),
    (3, 'EXPERIENCE_3', strings.EXPERIENCE_YEARS_CHOICES_3),
    (4, 'EXPERIENCE_4', strings.EXPERIENCE_YEARS_CHOICES_4),
    (5, 'EXPERIENCE_5', strings.EXPERIENCE_YEARS_CHOICES_5),
    (6, 'EXPERIENCE_6', strings.EXPERIENCE_YEARS_CHOICES_6),
    (7, 'EXPERIENCE_7', strings.EXPERIENCE_YEARS_CHOICES_7),
    (8, 'EXPERIENCE_8', strings.EXPERIENCE_YEARS_CHOICES_8),
    (9, 'EXPERIENCE_9', strings.EXPERIENCE_YEARS_CHOICES_9),
    (10, 'EXPERIENCE_10', strings.EXPERIENCE_YEARS_CHOICES_10),
    (11, 'EXPERIENCE_11', strings.EXPERIENCE_YEARS_CHOICES_11),
    (12, 'EXPERIENCE_12', strings.EXPERIENCE_YEARS_CHOICES_12),
    (13, 'EXPERIENCE_13', strings.EXPERIENCE_YEARS_CHOICES_13),
    (14, 'EXPERIENCE_14', strings.EXPERIENCE_YEARS_CHOICES_14),
])

GRADUATION_YEAR_CHOICES = Enumeration([
    (1, 'YEAR_1', strings.GRADUATION_YEAR_CHOICES_1),
    (2, 'YEAR_2', strings.GRADUATION_YEAR_CHOICES_2),
    (3, 'YEAR_3', strings.GRADUATION_YEAR_CHOICES_3),
    (4, 'YEAR_4', strings.GRADUATION_YEAR_CHOICES_4),
    (5, 'YEAR_5', strings.GRADUATION_YEAR_CHOICES_5),
    (6, 'YEAR_6', strings.GRADUATION_YEAR_CHOICES_6),
    (7, 'YEAR_7', strings.GRADUATION_YEAR_CHOICES_7),
    (8, 'YEAR_8', strings.GRADUATION_YEAR_CHOICES_8),
    (9, 'YEAR_9', strings.GRADUATION_YEAR_CHOICES_9),
])

JOB_POSITION_CHOICES = Enumeration([
    (1, 'JOB_POSITION_1', strings.JOB_POSITION_CHOICES_1),
    (2, 'JOB_POSITION_2', strings.JOB_POSITION_CHOICES_2),
    (3, 'JOB_POSITION_3', strings.JOB_POSITION_CHOICES_3),
    (4, 'JOB_POSITION_4', strings.JOB_POSITION_CHOICES_4),
    (5, 'JOB_POSITION_5', strings.JOB_POSITION_CHOICES_5),
    (6, 'JOB_POSITION_6', strings.JOB_POSITION_CHOICES_6),
])

# QuestionnaireForm error codes
QUESTIONNAIRE_FORM_INCOMPLETE_FORM_ERROR_CODE = 1000

# Resume's constants
RESUME_CV_FILE_MAX_UPLOAD_SIZE = 1048576 # 1MB
RESUME_CV_FILE_CONTENT_TYPES = (
    unicode(mime.Types.of('pdf')[0]),
    unicode(mime.Types.of('doc')[0]),
    unicode(mime.Types.of('docx')[0]),
)
