# -*- coding:utf-8 -*-
EMAIL_DOMAIN = 'mailinator.com'
EMPLOYER_EMAIL_USERNAME = 'employer'
EMPLOYEE_EMAIL_USERNAME = 'employee'
USER_PASSWORD = 'test123'
TOTAL_EMPLOYERS = 50
TOTAL_EMPLOYEES = 50
POSTINGS_PER_EMPLOYER_MIN = 0
POSTINGS_PER_EMPLOYER_MAX = 60
PRAXIS_PER_EMPLOYER_MIN = 0
PRAXIS_PER_EMPLOYER_MAX = 3
TOTAL_POSTINGS = 3000
